# Generated by Django 4.1.3 on 2023-02-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_trigram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fan_social_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_type',
            field=models.CharField(choices=[('F', 'Free'), ('S', 'Social'), ('SS', 'Super Social'), ('SDS', 'Super Duper Social'), ('FS', 'Fan Social')], default='Free', max_length=100),
        ),
    ]
