# Generated by Django 4.1.3 on 2023-03-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_fan_social_month_alter_profile_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_photo_added',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
