# Generated by Django 4.1.3 on 2023-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_last_photo_added_profile_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_photo_added',
        ),
        migrations.AddField(
            model_name='profile',
            name='selfie_verification',
            field=models.BooleanField(default=False),
        ),
    ]
