# Generated by Django 4.1.3 on 2023-03-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_profile_last_photo_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_link', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField()),
                ('event_created_date_time', models.DateTimeField(auto_now_add=True)),
                ('player1_username', models.CharField(max_length=255)),
                ('player2_username', models.CharField(max_length=255)),
                ('player1_decision', models.BooleanField(default=None)),
                ('player2_decision', models.BooleanField(default=None)),
            ],
        ),
    ]
