# Generated by Django 4.1.3 on 2023-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_profile_country_alter_profile_timezoneutc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sub_time_period',
            field=models.CharField(choices=[('F', 'Free'), ('M', 'Month'), ('Y', 'Year')], default='F', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_type',
            field=models.CharField(choices=[('F', 'Free'), ('S', 'Social'), ('SS', 'Super Social'), ('SDS', 'Super Duper Social'), ('FS', 'Fan Social')], default='F', max_length=100),
        ),
    ]
