# Generated by Django 4.1.3 on 2023-04-08 09:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_profile_available_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='available_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='available_time',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('8am-12pm', '8am-12pm'), ('12pm-4pm', '12pm-4pm'), ('4pm-8pm', '4pm-8pm'), ('8pm-10pm', '8pm-10pm')], default=[], max_length=100),
        ),
    ]
