# Generated by Django 4.1.3 on 2023-04-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_profile_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calendar',
            field=models.CharField(blank=True, choices=[('Google Calendar', 'Google Calendar'), ('Apple Calendar', 'Apple Calendar')], default='', max_length=255),
        ),
    ]
