# Generated by Django 4.1.3 on 2023-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_profile_timezoneutc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo3',
        ),
        migrations.AddField(
            model_name='profile',
            name='face_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
