# Generated by Django 4.1.3 on 2023-04-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_profile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
