# Generated by Django 4.1.3 on 2023-04-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_profile_content_type_profile_object_id_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav1_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav1_wiki_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav2_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav2_wiki_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav3_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav3_wiki_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav4_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav4_wiki_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav5_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav5_wiki_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='object_id',
        ),
    ]
