# Generated by Django 4.1.3 on 2023-04-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_profile_content_type_remove_profile_fav1_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
