# Generated by Django 4.1.3 on 2023-05-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_favorite_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
