# Generated by Django 4.1.3 on 2023-05-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_events_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_created_date_time',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_date_time',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_link',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_wiki_id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='player1_decision',
        ),
        migrations.RemoveField(
            model_name='events',
            name='player1_username',
        ),
        migrations.RemoveField(
            model_name='events',
            name='player2_decision',
        ),
        migrations.RemoveField(
            model_name='events',
            name='player2_username',
        ),
    ]
