# Generated by Django 4.1.3 on 2023-05-01 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0024_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('event_name', models.CharField(max_length=255)),
                ('event_link', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField()),
                ('event_created_date_time', models.DateTimeField(auto_now_add=True)),
                ('player1_decision', models.BooleanField(default=None, null=True)),
                ('player2_decision', models.BooleanField(default=None, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_profile', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
