# Generated by Django 4.1.3 on 2023-05-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_profile', to='home.profile'),
        ),
        migrations.AlterField(
            model_name='events',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_profile', to='home.profile'),
        ),
    ]
