# Generated by Django 4.1.3 on 2023-05-02 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_roommember_videoeventpoints_video_event_logs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Favorite_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managingrooms',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManagingRooms_player1_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managingrooms',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManagingRooms_player2_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video_event_logs',
            name='playedwith',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Video_Event_Logs_playedwith', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoeventpoints',
            name='accused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accused_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoeventpoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideoEventPoints_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
