# Generated by Django 4.1.3 on 2023-05-02 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_alter_favorite_profile_alter_managingrooms_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_player1_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_player2_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
