# Generated by Django 4.1.3 on 2023-05-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0030_alter_events_player1_alter_events_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managingrooms',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagingRooms_player1_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managingrooms',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagingRooms_player2_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
