# Generated by Django 4.1.3 on 2023-05-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_profile_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='player1_joined',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='player1_liked',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='player2_joined',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='player2_liked',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
