# Generated by Django 4.1.3 on 2023-05-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_events_player1_joined_events_player1_liked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='calendar',
        ),
    ]
