# Generated by Django 4.1.3 on 2023-05-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_profile_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='dumdumsocial_movie_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('wiki_id', models.CharField(max_length=255)),
                ('imdb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dumdumsocial_seires_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=255)),
                ('wiki_id', models.CharField(max_length=255)),
                ('imdb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
