# Generated by Django 4.1.3 on 2023-05-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_dumdumsocial_movie_character_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dumdumsocial_movie_character_img',
            old_name='year',
            new_name='release_year',
        ),
    ]
