# Generated by Django 4.1.3 on 2023-05-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_year_dumdumsocial_movie_character_img_release_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dumdumsocial_movie_character_img',
        ),
        migrations.DeleteModel(
            name='dumdumsocial_series_character_img',
        ),
    ]
